language: node_js
node_js:
    - "12.13.0"
dist: bionic
addons:
    ssh_known_hosts:
    - konasov.space
    chrome: stable
    
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_ec161a670f94_key -iv $encrypted_ec161a670f94_iv
  -in .travis/deploy_rsa.enc -out .travis/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
script: npm run test && npm run build:ssr
deploy:
    - provider: script
      skip_cleanup: true
      script: ".travis/deploy.sh"
      on:
        branch: master
